Added: Search-bar in monitoring table
bench-routes/bench-routes pull request #388
Opened 2021-03-19 06:12 UTC by rishav4101

Description : Search-bar is added in monitoring table for better and improved user experience.
Signed off by : @rishav4101 rajkumarrishav4101@gmail.com
Fixes : #384 
Proof :
![searchbar](https://user-images.githubusercontent.com/55195287/111738861-14d02280-88a8-11eb-8c18-87054e009c73.png)

2021-03-19 06:23 UTC, rishav4101 commented
@muskankhedia @Harkishen-Singh Kindly review it.

2021-03-19 08:28 UTC, aquibbaig requested changes

2021-03-19 08:28 UTC, aquibbaig commented on dashboard/v1.1/src/pages/Monitoring/Matrix.tsx
> +      <SearchBar
Please add proper styling to your components before you request a review. After you have done that, you can re-request a review in the PR settings(if you have access to).

2021-03-21 08:07 UTC, muskankhedia commented
@rishav4101 Can you please add the search bar as implemented over here?

<img width="1786" alt="Screenshot 2021-03-21 at 1 35 38 PM" src="https://user-images.githubusercontent.com/36980003/111898176-7b8d4180-8a4a-11eb-9d82-59bfbdc720db.png">

2021-03-22 04:16 UTC, muskankhedia commented
@rishav4101 Can you please update the screenshot in the description?

2021-03-22 04:17 UTC, muskankhedia commented
@rishav4101 The implementation looks good. Can you please make the search bar compatible with the dark mode?

<img width="1790" alt="Screenshot 2021-03-22 at 9 47 10 AM" src="https://user-images.githubusercontent.com/36980003/111939989-a384af80-8af3-11eb-83fb-bd8144371b68.png">

2021-03-22 04:23 UTC, rishav4101 commented
@muskankhedia Yes sure will update the code soon. Thank you.

2021-03-23 12:40 UTC, rishav4101 commented
@muskankhedia I have updated the code, Kindly review it.

2021-03-25 04:10 UTC, muskankhedia approved these changes
LGTM! Thank you for the PR!

2021-03-25 04:11 UTC, merged