Added: dark-mode to Graphs/Charts
bench-routes/bench-routes pull request #389
Opened 2021-03-19 07:28 UTC by rishav4101

Description : Graphs and Charts in dark-mode.
Signed off by : @rishav4101 rajkumarrishav4101@gmail.com
Fixes : #386 
Proof :
![ano](https://user-images.githubusercontent.com/55195287/111745279-5ebe0600-88b2-11eb-9751-2010a3c0b059.png)
![darkgraph](https://user-images.githubusercontent.com/55195287/111745284-5fef3300-88b2-11eb-83fd-dfaa2c0e915b.png)

2021-03-19 07:36 UTC, rishav4101 commented
@Harkishen-Singh @muskankhedia Please review it.

2021-03-19 08:21 UTC, aquibbaig requested changes
Hey, thanks for this PR! I can see that my browser freezes for a couple of seconds when I toggle dark mode, (dark mode should be seamless). There are a couple of reasons why it may happen and how we can fix it.
## Multiple references of localStorage in our code
 - jsperf says that the read performance of `localStorage` is significantly less than `native`. It may have less effect on real world uses but even if it doesn't, we must look for best practices here.
 - The solution here is to gather all references of theme variable and create a context variable in any top-level component and pass this as a prop to page component where you can say `const { darkMode } = useContext(Theme)`. 
## Multiple re-renders of charts cause the page to freeze.
- Since on a dark mode, we re-render charts with all their data in memory, this can be a costly operation.
- The solution here is to use code-splitting and use `React.Suspense` and `React.lazy` to show loaders until the charts are loaded and display them after that.

2021-03-19 08:21 UTC, aquibbaig commented on dashboard/v1.1/src/pages/Dashboard/CPUUsage.tsx
> +      mode: localStorage.getItem('dark-mode') === 'true' ? 'dark' : 'light'
Let's not reference localStorage in every case, what I'd say is to use localStorage once(if you can) in any top-level component and pass it as a context variable. The issue is that the read performance of localStorage can be costly at times. I've noticed my browser freezing on this branch and referencing localStorage constantly can be a cause. Also if all the charts have the same theme prop, what about instantiating it once and referencing it everywhere.

2021-03-20 09:11 UTC, muskankhedia commented
@rishav4101 Can you please fix this?

<img width="1790" alt="Screenshot 2021-03-20 at 2 37 22 PM" src="https://user-images.githubusercontent.com/36980003/111864999-5c2edf80-898a-11eb-8672-f5d0c27a1fa2.png">

2021-03-21 13:53 UTC, rishav4101 commented
@muskankhedia @aquibbaig Kindly review it.

2021-03-22 05:53 UTC, muskankhedia commented
@rishav4101 Can you please squash all the commits to one commit?

2021-03-22 05:55 UTC, muskankhedia requested changes
Can you please fix the graph on the `monitoring` and `tests` screen as well?

<img width="1787" alt="Screenshot 2021-03-22 at 11 24 51 AM" src="https://user-images.githubusercontent.com/36980003/111946295-3aa43400-8b01-11eb-9b7f-7bba9cb6e694.png">

<img width="1790" alt="Screenshot 2021-03-22 at 11 25 55 AM" src="https://user-images.githubusercontent.com/36980003/111946398-6cb59600-8b01-11eb-924e-abb6feb3c690.png">

2021-03-22 16:11 UTC, muskankhedia commented
@rishav4101 If you check the `Files changed` now, you could see the previously edited files have been edited in your commit. I will advise you to create a new PR only with your changes or revert the changes in the files that aren't a part of this PR. Can you please pick any one of the option and edit accordingly?

2021-03-23 10:46 UTC, rishav4101 commented
Yes, I will create a new PR for the change.

2021-03-23 14:29 UTC, rishav4101 commented
I have created a new PR #420, closing this one.

2021-03-23 14:29 UTC, closed without merging