Fixed syntax error in async await
bench-routes/bench-routes pull request #458
Opened 2021-04-03 09:53 UTC by 2019UCP1350

The wrong syntax was creating an error so I fixed it up.

2021-04-05 05:55 UTC, aquibbaig requested changes

2021-04-05 05:55 UTC, aquibbaig commented on dashboard/v1.1/src/pages/Input/Input.tsx
> +      }catch (err) {
Let's add a ' ' before catch.

2021-04-05 10:01 UTC, 2019UCP1350 commented on dashboard/v1.1/src/pages/Input/Input.tsx
> +      }catch (err) {
@aquibbaig  
added a  space before catch

2021-04-09 17:03 UTC, aquibbaig approved these changes
LGTM!

2021-04-11 11:29 UTC, Harkishen-Singh approved these changes
Thank you for the fix!

2021-04-11 11:29 UTC, merged